engine/src/main/java/org/archive/crawler/restlet/models/BeansModel.java
package org.archive.crawler.restlet.models;

import java.util.Collection;
import java.util.LinkedHashMap;

@SuppressWarnings("serial")
public class BeansModel extends LinkedHashMap<String, Object> {

    public BeansModel(String crawlJobShortName, String crawlJobUrl,
            String beanPath, Object bean, boolean editable, String problem,
            Object target, Collection<Object> allNamedCrawlBeans) {
        super();
        this.put("crawlJobShortName", crawlJobShortName);
        this.put("crawlJobUrl", crawlJobUrl);
        this.put("beanPath", beanPath);
        this.put("bean", bean);
        this.put("editable", editable);
        this.put("problem", problem);
        this.put("target", target);
        this.put("allNamedCrawlBeans", allNamedCrawlBeans);
    }
}

engine/src/main/java/org/archive/crawler/restlet/models/CrawlJobModel.java
package org.archive.crawler.restlet.models;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.commons.io.filefilter.IOFileFilter;
import org.archive.checkpointing.Checkpoint;
import org.archive.crawler.framework.CrawlController.State;
import org.archive.crawler.framework.CrawlJob;
import org.archive.crawler.reporting.Report;
import org.archive.spring.ConfigPath;
import org.archive.util.ArchiveUtils;
import org.archive.util.FileUtils;

@SuppressWarnings("serial")
public class CrawlJobModel extends LinkedHashMap<String, Object> implements Serializable{

    private CrawlJob crawlJob;
    public static final IOFileFilter EDIT_FILTER = FileUtils
            .getRegexFileFilter(".*\\.((c?xml)|(txt))$");
    
    public CrawlJobModel(CrawlJob crawlJob, String urlBaseRef){
        super();
        this.crawlJob=crawlJob;
        this.put("shortName",crawlJob.getShortName());
        if (crawlJob.getCrawlController() != null) {
            this.put("crawlControllerState", crawlJob.getCrawlController().getState());
            if (crawlJob.getCrawlController().getState() == State.FINISHED) {
                this.put("crawlExitStatus", crawlJob.getCrawlController().getCrawlExitStatus());
            }
        }

        this.put("statusDescription", crawlJob.getJobStatusDescription());
        Set<String> actions = new LinkedHashSet<String>();
        this.put("availableActions",actions);
    
        this.put("launchCount", crawlJob.getLaunchCount());
        this.put("lastLaunch",crawlJob.getLastLaunch());
        this.put("isProfile", crawlJob.isProfile());

        File primaryConfig = FileUtils.tryToCanonicalize(crawlJob.getPrimaryConfig());
        this.put("primaryConfig", primaryConfig.getAbsolutePath());
        this.put("primaryConfigUrl", urlBaseRef + "jobdir/" + primaryConfig.getName());
        this.put("url",urlBaseRef+"job/"+crawlJob.getShortName());

        this.put("jobLogTail", generateJobLogTail());
        this.put("uriTotalsReport", crawlJob.uriTotalsReportData());
        
        
        Map<String, Long> sizeTotalsReportData = crawlJob.sizeTotalsReportData();
        if (sizeTotalsReportData == null) {
            sizeTotalsReportData = new LinkedHashMap<String, Long>();
        }
        if (!sizeTotalsReportData.containsKey("dupByHash")) {
            sizeTotalsReportData.put("dupByHash", 0L);
        }
        if (!sizeTotalsReportData.containsKey("dupByHashCount")) {
            sizeTotalsReportData.put("dupByHashCount", 0L);
        }
        if (!sizeTotalsReportData.containsKey("novel")) {
            sizeTotalsReportData.put("novel", 0L);
        }
        if (!sizeTotalsReportData.containsKey("novelCount")) {
            sizeTotalsReportData.put("novelCount", 0L);
        }
        if (!sizeTotalsReportData.containsKey("notModified")) {
            sizeTotalsReportData.put("notModified", 0L);
        }
        if (!sizeTotalsReportData.containsKey("notModifiedCount")) {
            sizeTotalsReportData.put("notModifiedCount", 0L);
        }
        if (!sizeTotalsReportData.containsKey("total")) {
            sizeTotalsReportData.put("total", 0L);
        }
        if (!sizeTotalsReportData.containsKey("totalCount")) {
            sizeTotalsReportData.put("totalCount", 0L);
        }
        this.put("sizeTotalsReport", sizeTotalsReportData);
        
        this.put("rateReport", crawlJob.rateReportData());
        this.put("loadReport", crawlJob.loadReportData());
        this.put("elapsedReport", crawlJob.elapsedReportData()); 
        this.put("threadReport", crawlJob.threadReportData()); 
        this.put("frontierReport", crawlJob.frontierReportData());
        this.put("crawlLogTail", generateCrawlLogTail());
        this.put("configFiles",generateConfigReferencedPaths(urlBaseRef));


        this.put("isLaunchInfoPartial", crawlJob.isLaunchInfoPartial());
        this.put("isRunning", crawlJob.isRunning());
        this.put("isLaunchable",crawlJob.isLaunchable());
        this.put("hasApplicationContext",crawlJob.hasApplicationContext());
        this.put("alertCount", crawlJob.getAlertCount());        

        
        if (!crawlJob.hasApplicationContext())
            actions.add("build");

        if (!crawlJob.isProfile() && crawlJob.isLaunchable())
            actions.add("launch");
        if (crawlJob.isPausable())
            actions.add("pause");
        if (crawlJob.isUnpausable())
            actions.add("unpause");

        if (crawlJob.getCheckpointService() != null && crawlJob.isRunning())
            actions.add("checkpoint");
        if (crawlJob.isRunning())
            actions.add("terminate");
        if (crawlJob.hasApplicationContext())
            actions.add("teardown");

        if (crawlJob.getCheckpointService() != null) {
            Checkpoint recoveryCheckpoint = crawlJob.getCheckpointService().getRecoveryCheckpoint();
            if (recoveryCheckpoint != null)
                this.put("checkpointName", recoveryCheckpoint.getName());
        }
        
        List<String> checkpointFiles = new ArrayList<String>();
        if (crawlJob.getCheckpointService() != null) {
            if (crawlJob.isLaunchable() && crawlJob.getCheckpointService().hasAvailableCheckpoints()) {
                for (File f : crawlJob.getCheckpointService().findAvailableCheckpointDirectories()) {
                    checkpointFiles.add(f.getName()); 
                }
            }
        }
        this.put("checkpointFiles",checkpointFiles);
        if (crawlJob.hasApplicationContext())
            this.put("alertLogFilePath",crawlJob.getCrawlController().getLoggerModule().getAlertsLogPath().getFile().getAbsolutePath());
        if(crawlJob.isRunning() || (crawlJob.hasApplicationContext() && !crawlJob.isLaunchable()))
            this.put("crawlLogFilePath",crawlJob.getCrawlController().getLoggerModule().getCrawlLogPath().getFile().getAbsolutePath());
        this.put("reports", generateReports());
    }
    public String formatBytes(Long bytes){
        return ArchiveUtils.formatBytesForDisplay(bytes);
    }
    public String doubleToString(double number, int digits){
        return ArchiveUtils.doubleToString(number, digits);
    }
    public String getLastLaunchTime(){
        long ago = System.currentTimeMillis()
                - crawlJob.getLastLaunch().getMillis();
        return ArchiveUtils.formatMillisecondsToConventional(ago, 2);
    }
    /*
     * Alternative access to the file object, full name stored in base data map.
     */
    public File getConfigurationFilePath(){
        return crawlJob.getPrimaryConfig();
    }
    
    public List<String> generateJobLogTail(){
        List<String> jobLog = new ArrayList<String>();
        if (crawlJob.getJobLog().exists()) {
            try {
                FileUtils.pagedLines(crawlJob.getJobLog(), -1, -5, jobLog);
                Collections.reverse(jobLog);
            } catch (IOException ioe) {
                return null;
            }
        }
        return jobLog;
    }
    public List<String> generateCrawlLogTail() {
        List<String> logLines = new LinkedList<String>();
        if ((crawlJob.isRunning() || (crawlJob.hasApplicationContext() && !crawlJob.isLaunchable()))
                && crawlJob.getCrawlController().getLoggerModule()
                        .getCrawlLogPath().getFile().exists()) {
            try {
                FileUtils.pagedLines(crawlJob.getCrawlController()
                        .getLoggerModule().getCrawlLogPath().getFile(), -1,
                        -10, logLines);
                Collections.reverse(logLines);
            } catch (IOException ioe) {
                return null;
            }
        }
        return logLines;
    }
    public List<Map<String,String>> generateReports(){
        List<Map<String,String>> reports = new ArrayList<Map<String,String>>();
        if(crawlJob.hasApplicationContext()){
            for (Report report : crawlJob.getCrawlController().getStatisticsTracker().getReports()) {
                if (report.getShouldReportDuringCrawl()) {
                    Map<String,String> reportMap = new LinkedHashMap<String,String>();
                    String className = report.getClass().getSimpleName();
                    reportMap.put("className", className);
                    reportMap.put("shortName",className.substring(0,className.length() - "Report".length()));
                    reports.add(reportMap);
                }
            }
        }
        return reports;
    }
    private List<Map<String,Object>> generateConfigReferencedPaths(String baseRef){
        List<Map<String,Object>> referencedPaths = new ArrayList<Map<String,Object>>();
        for (String key : crawlJob.getConfigPaths().keySet()) {
            ConfigPath cp = crawlJob.getConfigPaths().get(key);
            Map<String,Object> configMap = new LinkedHashMap<String,Object>();
            configMap.put("key", key);
            configMap.put("name", cp.getName());
            configMap.put("path",FileUtils.tryToCanonicalize(cp.getFile()).getAbsolutePath());
            configMap.put("url",baseRef+"engine/anypath/"+configMap.get("path"));
            configMap.put("editable", EDIT_FILTER.accept(cp.getFile()));
            referencedPaths.add(configMap);
        }
        return referencedPaths;
    }
}

engine/src/main/java/org/archive/crawler/restlet/models/EngineModel.java
package org.archive.crawler.restlet.models;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import org.archive.crawler.framework.CrawlController.State;
import org.archive.crawler.framework.CrawlJob;
import org.archive.crawler.framework.Engine;
import org.archive.util.FileUtils;

@SuppressWarnings("serial")
public class EngineModel extends LinkedHashMap<String, Object> {
    
    public EngineModel(Engine engine, String urlBaseRef){
        super();
        this.put("heritrixVersion", engine.getHeritrixVersion());
        this.put("heapReport", engine.heapReportData());
        this.put("jobsDir", FileUtils.tryToCanonicalize(engine.getJobsDir()).getAbsolutePath());
        this.put("jobsDirUrl", urlBaseRef + "jobsdir/");
        
        List<String> actions = new LinkedList<String>();
        actions.add("rescan");
        actions.add("add");
        actions.add("create");
        this.put("availableActions", actions);
        
        this.put("jobs", makeJobList(engine, urlBaseRef));
    }

	private List<Map<String, Object>> makeJobList(Engine engine,
			String urlBaseRef) {
		List<Map<String, Object>> jobList;
		jobList = new ArrayList<Map<String,Object>>();
        // Generate list of jobs
        ArrayList<Map.Entry<String,CrawlJob>> jobConfigurations = new ArrayList<Map.Entry<String,CrawlJob>>(engine.getJobConfigs().entrySet());
        Collections.sort(jobConfigurations, new Comparator<Map.Entry<String, CrawlJob>>() {
            public int compare(Map.Entry<String, CrawlJob> cj1, Map.Entry<String, CrawlJob> cj2) {
                return cj1.getValue().compareTo(cj2.getValue());
            }
        });
        
        for(Map.Entry<String,CrawlJob> jobConfig : jobConfigurations) {
            CrawlJob job = jobConfig.getValue();
            Map<String, Object> crawlJobModel = new LinkedHashMap<String, Object>();
            crawlJobModel.put("shortName",job.getShortName());
            crawlJobModel.put("url",urlBaseRef+"job/"+job.getShortName());
            crawlJobModel.put("isProfile",job.isProfile());
            crawlJobModel.put("launchCount",job.getLaunchCount());
            crawlJobModel.put("lastLaunch",job.getLastLaunch());
            crawlJobModel.put("hasApplicationContext",job.hasApplicationContext());
            crawlJobModel.put("statusDescription", job.getJobStatusDescription());
            crawlJobModel.put("isLaunchInfoPartial", job.isLaunchInfoPartial());
            File primaryConfig = FileUtils.tryToCanonicalize(job.getPrimaryConfig());
            crawlJobModel.put("primaryConfig", primaryConfig.getAbsolutePath());
            crawlJobModel.put("primaryConfigUrl", urlBaseRef + "jobdir/" + primaryConfig.getName());
            if (job.getCrawlController() != null) {
                crawlJobModel.put("crawlControllerState", job.getCrawlController().getState());
                if (job.getCrawlController().getState() == State.FINISHED) {
                    crawlJobModel.put("crawlExitStatus", job.getCrawlController().getCrawlExitStatus());
                }
            }
            
            crawlJobModel.put("key", jobConfig.getKey());
            jobList.add(crawlJobModel);
        }
		return jobList;
	}
}

engine/src/main/java/org/archive/crawler/restlet/models/ScriptModel.java
package org.archive.crawler.restlet.models;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.archive.crawler.restlet.ScriptingConsole;

@XmlRootElement(name="script")
@XmlType(propOrder={
        "crawlJobUrl", "crawlJobShortName", "availableScriptEngines", 
        "script", "linesExecuted", "exception", "rawOutput", "htmlOutput",
        "availableGlobalVariables"
})
public class ScriptModel {
    private String crawlJobUrl;
    private Collection<Map<String, String>> availableScriptEngines;
    private ScriptingConsole scriptingConsole;

	public ScriptModel(ScriptingConsole cc,
	        String crawlJobUrl,
			Collection<Map<String, String>> scriptEngines) {
	    scriptingConsole = cc;
	    this.crawlJobUrl = crawlJobUrl;
	    this.availableScriptEngines = scriptEngines;
    }
	
    public boolean isFailure() {
        return scriptingConsole.getException() != null;
    }
    public String getStackTrace() {
        Throwable exception = scriptingConsole.getException();
        if (exception == null) return "";
        StringWriter s = new StringWriter();
        exception.printStackTrace(new PrintWriter(s));
        return s.toString();
    }
    public Throwable getException() {
        return scriptingConsole.getException();
    }
    public int getLinesExecuted() {
        return scriptingConsole.getLinesExecuted();
    }
    public String getRawOutput() {
        return scriptingConsole.getRawOutput();
    }
    public String getHtmlOutput() {
        return scriptingConsole.getHtmlOutput();
    }
    public String getScript() {
        return scriptingConsole.getScript();
    }
    
    public String getCrawlJobShortName() {
        return scriptingConsole.getCrawlJob().getShortName();
    }
    public Collection<Map<String, String>> getAvailableScriptEngines() {
        return availableScriptEngines;
    }
    public List<Map<String, String>> getAvailableGlobalVariables() {
        return scriptingConsole.getAvailableGlobalVariables();
    }
    public String getCrawlJobUrl() {
        return crawlJobUrl;
    }
}

engine/src/main/java/org/archive/crawler/restlet/models/ViewModel.java
package org.archive.crawler.restlet.models;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.archive.crawler.restlet.Flash;

@SuppressWarnings("serial")
public class ViewModel extends LinkedHashMap<String,Object> {
    public ViewModel(){
        super();
    }
    public void setFlashes(List<Flash> flashes){
        List<Map<String,Object>> flashList = new ArrayList<Map<String,Object>>();
        this.put("flashes", flashList);
        for(Flash flash: flashes) {
            Map<String, Object> flashModel = new HashMap<String, Object>();
            flashModel.put("kind", flash.getKind());
            flashModel.put("message", flash.getMessage());
            flashList.add(flashModel);
        }
    }
}

engine/src/main/resources/org/archive/crawler/restlet/Beans.ftl
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="/engine/static/css/normalize.css" />
	<link rel="stylesheet" href="/engine/static/css/foundation.min.css" />
	<link rel="stylesheet" href="/engine/static/css/heritrix.css" />
	<script src="/engine/static/js/vendor/custom.modernizr.js"></script>
	
	<title>Crawl beans in ${model.crawlJobShortName}</title>
	
</head>
<body>
	<div class="contain-to-grid">
		<nav class="top-bar">
			<ul class="title-area">
				<li class=" name">
					<h1>
						<img alt="Heritrix" class="hide-for-small"
							style="padding-top: 4px;"
							src="/engine/static/img/heritrix-logo.gif" /> <span
							class="hide-for-medium-up">Heritrix</span>
					</h1>
				</li>
				<li class="toggle-topbar menu-icon left"><a href="#"><span>Menu</span></a></li>
			</ul>

			<section class="top-bar-section">
				<!-- Left Nav Section -->
				<ul class="right">

					<li class="divider"></li>
					<li><a href="/engine">Engine</a></li>
					<li class="divider"></li>
					<li><a href="/engine/job/${model.crawlJobShortName}">Job "${model.crawlJobShortName}"</a></li>
					<li class="divider"></li>
				</ul>
			</section>
		</nav>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<h3>Crawl beans in built job <i><a href='/engine/job/${model.crawlJobShortName}'>${model.crawlJobShortName}</a></i></h3>
			<div class="row">
				<div class="large-12 columns">
					<div class="panel">
							Enter a bean path of the form <i>beanName</i>, <i>beanName.property</i>, <i>beanName.property[indexOrKey]</i>, etc.
							<form method='POST'>
								<input class="inline" type='text' name='beanPath' style='width:60%;margin:0' value='${model.beanPath}'>
								<input class="small inline button" type='submit' value='view'>
							</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	
<#if model.beanPath?? && (model.beanPath?length >0)>
	<div class="row">
		<div class="large-12 columns">
			<h3>Bean path <i>${model.beanPath}</i></h3>
			<div class="row">
				<div class="small-12 columns">
					<#if model.problem??>
						<div class="panel">
							<i style='color:red'>problem: ${model.problem}</i>
						</div>
					<#elseif model.editable>
						<div class="panel">
							<div>
								${model.beanPath} = 
								<@beanTemplate bean=model.bean />  <a href="javascript:document.getElementById('editform').style.display='block';void(0);">edit</a>
							</div>
							<form id='editform' style='display:none' method='POST'>
								<div>Note: it may not be appropriate/effective to change this value in an already-built crawl context.</div>
								<div><input type='hidden' name='beanPath' value='${model.beanPath}'>
									${model.beanPath} = <input type='text' name='newVal' style='width:400px' value='<#if model.target?is_number>${model.target?c}<#else>${model.target?string}</#if>'>
									<input type='submit' value='update'>
								</div>
							</form>
						</div>
					<#else>
						<@beanTemplate bean=model.bean />
					</#if>
				</div>
				
			</div>
		</div>
	</div>
							
							
</#if>
	<div class="row">
		<div class="large-12 columns">
			<h3>All named crawl beans</h3>
			<div class="row">
				<div class="small-12 columns">
					<div class="panel">
						<ul>
						<#list model.allNamedCrawlBeans as bean>
							<@beanListItem bean=bean />
						</#list>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

<#macro beanListItem bean>
	<li>	<#-- have to use .get("class") instead of .class due to freemarker conflict with method getClass()-->
		<a href='${bean.url}'>${bean.name}</a><span style='color:#999'> ${bean.get("class")}</span>
		<ul>
			<#list bean.children as child>
			<@beanListItem bean=child />
			</#list>
		</ul>
	</li>
</#macro>

<#macro beanTemplate bean>
<#if bean.field?? && (bean.field?length>0)>
	<th>
		<b><#if bean.field?contains("#")>${bean.field}<#else><a href='${bean.url}'>${bean.field}</a></#if>:</b>
	</th>
</#if>
<td>
<#if bean.propValuePreviouslyDescribed??>
	&uarr;
<#elseif !bean.propValue?? && !bean.properties?? && !bean.get("class")??>
	<#if bean.key?? && bean.field??>
	<a href='../beans/${bean.key}'>${bean.key}</a>
	<#else>
	<i>null</i>
	</#if>
<#elseif bean.propValue?? && !bean.propValue?is_collection>
	<#if bean.get("class")?? && bean.get("class")?contains("String")>
	"${bean.propValue}"
	<#elseif bean.propValue?is_number>
	${bean.propValue?c}
	<#else>
	${bean.propValue?string}
	</#if>
</#if>

<#if (!bean.propValue?? && !bean.properties?? && bean.get("class")??) || bean.properties?? || (bean.propValue?? && bean.propValue?is_collection)>
<fieldset>
	<legend>${bean.get("class")}</legend>
	<table class="beans">
	<#if bean.properties??>
	<#list bean.properties as property>
		<tr><@beanTemplate bean=property /></tr>
	</#list>
	</#if>
	<#if bean.propValue?? && bean.propValue?is_collection>
		<#list bean.propValue as element>
		<tr><@beanTemplate bean=element /></tr>
		</#list>
	</#if>
	</table>
</fieldset>
</td>
</#if>
</#macro>

engine/src/main/resources/org/archive/crawler/restlet/Script.ftl
<!DOCTYPE html>
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="/engine/static/css/normalize.css" />
	<link rel="stylesheet" href="/engine/static/css/foundation.min.css" />
	<link rel="stylesheet" href="/engine/static/css/heritrix.css" />
	<script src="/engine/static/js/vendor/custom.modernizr.js"></script>
	
	<title>Script in ${model.crawlJobShortName}</title>
	
	<link rel='stylesheet' href='/engine/static/codemirror/codemirror.css'>
	<link rel='stylesheet' href='/engine/static/codemirror/util/dialog.css'>
	<script src='/engine/static/codemirror/codemirror.js'></script>
	<script src='/engine/static/codemirror/mode/groovy.js'></script>
	<script src='/engine/static/codemirror/mode/clike.js'></script>
	<script src='/engine/static/codemirror/mode/javascript.js'></script>
	<script src='/engine/static/codemirror/util/dialog.js'></script>
	<script src='/engine/static/codemirror/util/searchcursor.js'></script>
	<script src='/engine/static/codemirror/util/search.js'></script>
</head>
<body>
	<div class="contain-to-grid">
		<nav class="top-bar">
			<ul class="title-area">
				<li class=" name">
					<h1>
						<img alt="Heritrix" class="hide-for-small"
							style="padding-top: 4px;"
							src="/engine/static/img/heritrix-logo.gif" /> <span
							class="hide-for-medium-up">Heritrix</span>
					</h1>
				</li>
				<li class="toggle-topbar menu-icon left"><a href="#"><span>Menu</span></a></li>
			</ul>

			<section class="top-bar-section">
				<!-- Left Nav Section -->
				<ul class="right">
					<li class="divider"></li>
					<li><a href="/engine">Engine</a></li>
					<li class="divider"></li>
					<li><a href="/engine/job/${model.crawlJobShortName}">Job "${model.crawlJobShortName}"</a></li>
					<li class="divider"></li>
				</ul>
			</section>
		</nav>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<h3>Execute script for job <i><a href='/engine/job/${model.crawlJobShortName}'>${model.crawlJobShortName}</a></i></h3>
			<div class="row">
				<div class="large-12 columns">
					<div class="panel">
						<#if (model.linesExecuted > 0)>
						<span class='success'>${model.linesExecuted} ${(model.linesExecuted>1)?string("lines","line")} executed<span>
						</#if>
						<#if model.failure>
						<pre style='color:red; height:150px; overflow:auto'>${model.stackTrace}
						</pre>
						</#if>
						<#assign htmlOutput=model.htmlOutput>
						<#if (htmlOutput?length > 0)>
						<fieldset><legend>htmlOut</legend>
						${htmlOutput}
						</fieldset>
						</#if>
						<#assign rawOutput=model.rawOutput>
						<#if (rawOutput?length > 0)>
						<fieldset><legend>rawOutput</legend>
						<pre style="margin:0;">${rawOutput}
							</pre>
						</fieldset>
						</#if>
						<form method="POST">
							<div style="margin-bottom:1em">
								<label class="inline" for="engine">Script Engine: </label>
								<select class="inline" style="width:auto" name="engine" id="selectEngine">
									<#list model.availableScriptEngines as scriptEngine>
									<option<#if selectedEngine=scriptEngine.engine> selected='selected'</#if> value='${scriptEngine.engine}'>${scriptEngine.language}</option>
									</#list>
								</select>
								<input class="small inline button" type="submit" value="execute">
							</div>
							<textarea rows='20' style='width:100%' name='script' id='editor'>${(model.script)!""}</textarea>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="large-12 columns">
			The script will be executed in an engine preloaded with (global) variables:
			<ul class="no-bullet">
				<#list model.availableGlobalVariables as v>
				<li style="line-height:1"><code>${v.variable}</code>: ${v.description?html}</li>
				</#list>
			</ul>
		</div>
	</div>
<script>
	var modemap = {beanshell: 'text/x-java', groovy: 'groovy', js: 'javascript'};
	var selectEngine = document.getElementById('selectEngine');
	var editor = document.getElementById('editor');
	var cmopts = {
		    mode: modemap[selectEngine.value],
	        lineNumbers: true, autofocus: true, indentUnit: 4
		    }
	var cm = CodeMirror.fromTextArea(editor, cmopts);
	selectEngine.onchange = function(e) { cm.setOption('mode', modemap[selectEngine.value]); }
</script>

</body>
</html>